# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SplitTheTab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SplitTheTab
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'KRAlertController'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'


  target 'SplitTheTabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SplitTheTabUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
